import express from "express";
import RoleRouter from './roleRouter';
import TypeRouter from './typeRouter';
import SizeRouter from './sizeRouter';
import ColorRouter from './colorRouter';
import BrandRouter from './brandRouter';
import OriginRouter from './originRouter';
import DiscountRouter from './discountRouter';
import StatusRouter from './statusRouter';
import UserRouter from './userRouter';
import LoginRouter from './loginRouter';
import ProductRouter from './productRouter';
import User_addressRouter from './user_addressRouter';
import CartRouter from './cartRouter';
import PaymentRouter from './paymentRouter';
import OrderRouter from './orderRouter';
import OrderDetailRouter from './orderdetailRouter';
import User_roleRouter from './user_roleRouter';
import Detail from './detailRouter';
let router = express.Router();
let initWebRoutes = (app) => {
    RoleRouter(app);
    TypeRouter(app);
    SizeRouter(app);
    ColorRouter(app);
    BrandRouter(app);
    OriginRouter(app);
    DiscountRouter(app);
    StatusRouter(app);
    UserRouter(app);
    LoginRouter(app);
    ProductRouter(app);
    User_addressRouter(app);
    CartRouter(app);
    PaymentRouter(app);
    OrderRouter(app);
    OrderDetailRouter(app);
    User_roleRouter(app);
    Detail(app);
    return app.use("/", router);
}
module.exports = initWebRoutes;