const actionTypes = Object.freeze({
    TEST_START: "TEST_START",
    TEST_SUCCESS: "TEST_SUCCESS",
    TEST_FAILED: "TEST_FAILED",

    TEST_DATA: 'TEST_DATA',
    TEST_SUCCESS_DATA: "TEST_SUCCESS_DATA",

    GET_DATA_PRODUCT: 'GET_DATA_PRODUCT',
    FILTER_PRODUCT: 'FILTER_PRODUCT',
    GET_PRODUCT_ID: 'GET_PRODUCT_ID',
})

export default actionTypes;